-- IAST + ISO 15919 Cycle for Hammerspoon
-- Version 1.1 — fixes repeated-key cycling by ignoring events generated
-- by this script itself.
--
-- Normal typing is untouched. Hold Option and tap a supported base letter.
-- Repeated deliberate taps before releasing Option cycle through related forms.

local eventtap = hs.eventtap
local event = hs.eventtap.event
local types = event.types
local props = event.properties
local keycodes = hs.keycodes.map

local mappings = {
  a = { lower = {"ā"},             upper = {"Ā"} },
  i = { lower = {"ī"},             upper = {"Ī"} },
  u = { lower = {"ū"},             upper = {"Ū"} },
  e = { lower = {"ē"},             upper = {"Ē"} },
  o = { lower = {"ō"},             upper = {"Ō"} },
  r = { lower = {"ṛ", "ṝ", "ṟ"}, upper = {"Ṛ", "Ṝ", "Ṟ"} },
  l = { lower = {"ḷ", "ḻ", "ḹ"}, upper = {"Ḷ", "Ḻ", "Ḹ"} },
  s = { lower = {"ś", "ṣ"},       upper = {"Ś", "Ṣ"} },
  n = { lower = {"ṇ", "ñ", "ṅ"}, upper = {"Ṇ", "Ñ", "Ṅ"} },
  m = { lower = {"ṁ", "ṃ"},       upper = {"Ṁ", "Ṃ"} },
  t = { lower = {"ṭ"},             upper = {"Ṭ"} },
  d = { lower = {"ḍ"},             upper = {"Ḍ"} },
  h = { lower = {"ḥ"},             upper = {"Ḥ"} },
}

local keyByCode = {}
for key, _ in pairs(mappings) do
  keyByCode[keycodes[key]] = key
end

local lastKey = nil
local lastUpper = false
local cycleIndex = 0

-- A distinctive value placed on every keyboard event generated by this script.
-- The event tap ignores these events, preventing them from resetting the cycle.
local SYNTHETIC_TAG = 0x56494153 -- ASCII-ish: "VIAS"

local function resetCycle()
  lastKey = nil
  lastUpper = false
  cycleIndex = 0
end

local function markSynthetic(e)
  e:setProperty(props.eventSourceUserData, SYNTHETIC_TAG)
  return e
end

local function postUnicode(text)
  -- setUnicodeString clears modifier flags, so the physically held Option key
  -- is not inherited by the generated character.
  local down = event.newKeyEvent({}, keycodes.a, true)
  down:setUnicodeString(text)
  markSynthetic(down):post()

  local up = event.newKeyEvent({}, keycodes.a, false)
  up:setUnicodeString(text)
  markSynthetic(up):post()
end

local function pressDelete()
  markSynthetic(event.newKeyEvent({}, "delete", true)):post()
  markSynthetic(event.newKeyEvent({}, "delete", false)):post()
end

IASTypeCycleTap = eventtap.new({
  types.keyDown,
  types.flagsChanged,
  types.leftMouseDown,
  types.rightMouseDown,
  types.otherMouseDown,
}, function(e)
  -- Never let our own generated Unicode or Delete events alter cycle state.
  if e:getProperty(props.eventSourceUserData) == SYNTHETIC_TAG then
    return false
  end

  local eventType = e:getType()

  if eventType == types.flagsChanged then
    local flags = e:getFlags()
    if not flags.alt then resetCycle() end
    return false
  end

  if eventType == types.leftMouseDown
      or eventType == types.rightMouseDown
      or eventType == types.otherMouseDown then
    resetCycle()
    return false
  end

  local flags = e:getFlags()
  local key = keyByCode[e:getKeyCode()]

  -- Claim only Option+letter and Option+Shift+letter. Command, Control,
  -- and Fn combinations remain available to applications and macOS.
  if not flags.alt or flags.cmd or flags.ctrl or flags.fn or not key then
    resetCycle()
    return false
  end

  -- Suppress hardware auto-repeat; deliberate repeated taps still work.
  if e:getProperty(props.keyboardEventAutorepeat) == 1 then
    return true
  end

  local upper = flags.shift == true
  local variants = mappings[key][upper and "upper" or "lower"]

  if #variants > 1 and lastKey == key and lastUpper == upper then
    cycleIndex = (cycleIndex % #variants) + 1
    pressDelete()
    postUnicode(variants[cycleIndex])
  else
    cycleIndex = 1
    postUnicode(variants[cycleIndex])
  end

  lastKey = key
  lastUpper = upper
  return true
end)

IASTypeCycleTap:start()
hs.alert.show("IASType 1.1 enabled", 1.2)
